
# Standard site identity details
title: Example-Corp Policies
email: your-email@example.com
description: >-
  Modular corporate policy framework, built on Git, Markdown and Jekyll
  to make policies both transparent to inspection, discussion and challenge
  as well as easier to adopt, adapt and modify over time.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jerryjvl
github_username:  jerryjvl
timezone: America/Los_Angeles

# Standard build settings
markdown: redcarpet # kramdown
theme: minima
plugins:
  - jekyll-feed

# Additional build settings for jekyll-policy
header_pages: [index.md, content/blog.md, content/glossary.md, README.md]
strict_front_matter: true
collections_dir: content
data_dir: content/_data
liquid:
  error_mode: strict
redcarpet:
  extensions:
    - smart
    - no_intra_emphasis
    - autolink
    - tables
    - superscript # ^(xx) superscripts 'xx'
    - highlight # == around text marks it as highlighted